openapi: 3.1.0
info:
  title: iiko Actions Proxy
  version: 1.0.2
servers:
  - url: https://YOUR_APP.vercel.app
paths:
  /api/server/organizations:
    get:
      summary: Get organizations from iiko Server (internal auth handled)
      security:
        - BridgeKey: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  organizations:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }
                        name: { type: string }
  /api/cloud/organizations:
    post:
      summary: Get organizations from iiko Cloud v6
      security:
        - BridgeKey: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                organizationIds:
                  type: array
                  items: { type: string }
                returnExternalData:
                  type: boolean
      responses:
        "200":
          description: OK
  /api/health:
    get:
      summary: Health check (no auth)
      responses:
        "200":
          description: OK
components:
  securitySchemes:
    BridgeKey:
      type: apiKey
      in: header
      name: X-Bridge-Key
